✨ Movie: 007 Collection
jade-team/plex-meta-manager-config pull request #82
Opened 2024-01-06 10:37 UTC by jasimancas

2024-01-07 17:19 UTC, danimart1991 requested changes

2024-01-07 17:19 UTC, danimart1991 commented on metadata/movies/movies.yml
> +    title: "James Bond: Quatum of Solace"
`Quatum` -> `Quantum`

2024-01-07 19:52 UTC, jasimancas commented on metadata/movies/movies.yml
> +    title: "James Bond: Quatum of Solace"
Done

2024-01-08 07:27 UTC, danimart1991 approved these changes

2024-01-08 07:27 UTC, merged